# Generated by Django 6.0.1 on 2026-02-12 13:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_routepoint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='route',
            name='description',
        ),
        migrations.AddField(
            model_name='route',
            name='categories',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='route',
            name='city_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='route',
            name='end_point_address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='route',
            name='end_point_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='route',
            name='end_point_lon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='route',
            name='end_type',
            field=models.CharField(default='start', max_length=50),
        ),
        migrations.AddField(
            model_name='route',
            name='route_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='route',
            name='start_point_address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='route',
            name='start_point_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='route',
            name='start_point_lon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='route',
            name='total_distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='route',
            name='total_duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='route',
            name='walking_time',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='route',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='route',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
